name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
    - name: Lint with flake8
      run: |
        flake8 drf_logger example_project
    - name: Test with unittest
      run: |
        coverage run -m unittest discover tests
        coverage report -m
    - name: Test on django project
      run: |
        python setup.py develop
        cd example_project
        python manage.py test
        cd ../
    - name: Mypy type checking
      run: |
        mypy drf_logger
